### ISSUE TITLE
The last LI in the changelog always gets a h1 rendered into it, which is not selectable to be hidden with custom css

### ISSUE THREAD

**Issue by ThorbenKuck** [anikethsaha/docsify-plugin#60]
While integrating this plugin into the theme selector, I noticed that the last li in the list that is rendered by the changelog plugin always gets a nested h1 child element with the id "-3".

This is my markdown for the changelog:

```
# V 1.0.0 Alpha 2

_Second public release_

- Test

---

# V 1.0.0 Alpha 1

_First public release_

- Test
```

This compiles fine when viewed as a normal page:

![grafik](https://user-images.githubusercontent.com/18304597/161512432-1b59d43b-9f4f-4311-ab0f-96338e3269c2.png)

But when viewed in the rendered Changelog entry, it looks like this:

![grafik](https://user-images.githubusercontent.com/18304597/161512566-5ff37d63-fd80-4217-b723-0aa81c57c051.png)

Note the black bar in the last entry. This issue arose most notably as I tried to adjust the css to accommodate dark mode by integrating with their vars. This can also be verified by inspecting the element:

![grafik](https://user-images.githubusercontent.com/18304597/161513113-470358a5-5e3c-4f1e-ab5c-bcb3bc065886.png)

I guess this is a bug, because with the id -3, it appears to be not specifically selectable. The following selectors did not allow me to hide the last h1:

```css
#-3 { visibility: hidden !important; }
h1#-3 { visibility: hidden !important; }
#CHANGELOG_RENDERER h1#-3 { visibility: hidden !important; }
#CHANGELOG li > h1#-3 { visibility: hidden !important; }
#CHANGELOG li > h1 { visibility: hidden !important; }
```
